name: tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x
    - name: Restore dependencies
      run: dotnet restore ./Folleach.Vostok.Logging.Kafka.sln
    - name: Build
      run: dotnet build --no-restore ./Folleach.Vostok.Logging.Kafka.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Folleach.Vostok.Logging.Kafka.sln
